{% set name = "xpdacq" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xpdacq-{{ version }}.tar.gz
  sha256: 7e578d20d3f3c829f565f386b53185f6db22cec0a119adafc07b2d3f34712b21

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - pip
    - python >=3.8, <3.10

  run:
    - python >=3.8, <3.10
    - bluesky
    - bluesky-darkframes
    - frozendict
    - databroker <2.0.0a
    - ipython
    - numpy
    - openpyxl
    - ophyd
    - pandas
    - pyfai
    - pyopencl
    - pyyaml
    - xlrd
    - xpdconf >=0.4.5
    - xpdsim


test:
  imports:
    - xpdacq
    - xpdacq.xpdacq
    - xpdacq.beamtime

about:
  home: https://github.com/xpdAcq/xpdAcq
  summary: Acquisition packages for 28-ID beamlines at BNL
  doc_url: http://xpdacq.github.io/xpdAcq/
  dev_url: https://github.com/xpdAcq/xpdAcq
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sbillinge
    - st3107
