{% set name = "xpdacq" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xpdacq-{{ version }}.tar.gz
  sha256: be39446e15a055956b8f37c3556d7381f573383f9205e651388cbd1ad52c5216

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  host:
    - pip
    - python >=3.8

  run:
    - python >=3.8
    - bluesky
    - bluesky-darkframes
    - databroker
    - fabio
    - frozendict
    - ipython
    - numpy
    - openpyxl
    - ophyd
    - pandas
    - pyfai
    - pyopencl
    - pyyaml
    - tifffile
    - xlrd
    - xpdconf >=0.4.6
    - xpdsim >=0.4.3


test:
  imports:
    - xpdacq
    - xpdacq.xpdacq
    - xpdacq.beamtime

about:
  home: https://github.com/xpdAcq/xpdAcq
  summary: Acquisition packages for 28-ID beamlines at BNL
  doc_url: http://xpdacq.github.io/xpdAcq/
  dev_url: https://github.com/xpdAcq/xpdAcq
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sbillinge
    - st3107
