travis:
  secure:
    BINSTAR_TOKEN: w7aioDsLu2cJwNmRYWQK4sP4znFKwhkbkK8yaJsx8mMiYkYkxYae9kzu2ruGxX9OlT1mgsHuokSM9b2yJlGHSbHbDhHdSYAFZJj4B5+G9b8YK5Mhdybh9Aw1EzWSuf+QzpUl2+6dF+NDb6JnvaeOMWcUqt/IefPyKGkk5DcFTrLGNkW5HH0K+jhvnyXU21/7mwHOOutOk6XDq4Ps7AY/IRSBzPOCej/TQhg7zlpsyRKhjdWifRw2koROurn0BEG6gYIXT+RQxE4Hne88PgadQFWzJ94PqglDRlLzRCcNruTVzwLJQM6KtcAUikVzjdrx2y5mw7+2oe/ardcgMk6NIdg8NA5LAdIU5BcKRHYlpmQLhkd/1tjKvRzYy77MZ/X+OGZukWYP5ZsZSaMqkUYMlB40mCb/IVhpFrWMMnEqtyySQr89H46/2raHI4BhD0gO9uViLsvLgUsNQcJNvvttOO/lhzAXeDRwdEHkw42rBhEMIJ/io/SG3VoGyPbbRq4Lu0TnJ5ufwPl+G7QixsC0hclmoq965J4O9f6t8IvCBI9Xc6iJhAmHQ5UYWWCYruvR3HJ1E2Sbk3u0E+1lCH89My2vz6kNwCB5adR2S8vka4rmPOMtShYVVf+5+ZVewEEGRaxk0dCdPx98X1wSIj2ou8xJT42uvee/oFEARDm82YI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
